insert into role(name) values('User');
insert into role(name) values('Administrator');

insert into users(username,password) values('user', '{noop}user');
insert into users(username,password) values('admin', '{noop}admin');

insert into users_roles(roles_id, user_id) values(1, 1);
insert into users_roles(roles_id, user_id) values(1, 2);
insert into users_roles(roles_id, user_id) values(2, 2);

insert into price(amount, currency, deleted) values(1.49, 'EUR', false);
insert into price(amount, currency, deleted) values(2.49, 'EUR', false);
insert into price(amount, currency, deleted) values(3.49, 'EUR', false);

insert into product(name, price_id, deleted) values('One', 1, false);
insert into product(name, price_id, deleted) values('Two', 2, false);
insert into product(name, price_id, deleted) values('Three', 3, false);

insert into price(amount, currency, deleted) values(9.99, 'USD', false);
insert into product(name, price_id, deleted) values('Essence Mascara Lash Princess', 4, false);
insert into price(amount, currency, deleted) values(19.99, 'USD', false);
insert into product(name, price_id, deleted) values('Eyeshadow Palette with Mirror', 5, false);
insert into price(amount, currency, deleted) values(14.99, 'USD', false);
insert into product(name, price_id, deleted) values('Powder Canister', 6, false);
insert into price(amount, currency, deleted) values(12.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Red Lipstick', 7, false);
insert into price(amount, currency, deleted) values(8.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Red Nail Polish', 8, false);
insert into price(amount, currency, deleted) values(49.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Calvin Klein CK One', 9, false);
insert into price(amount, currency, deleted) values(129.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Chanel Coco Noir Eau De', 10, false);
insert into price(amount, currency, deleted) values(89.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Dior Jadore', 11, false);
insert into price(amount, currency, deleted) values(69.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Dolce Shine Eau de', 12, false);
insert into price(amount, currency, deleted) values(79.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Gucci Bloom Eau de', 13, false);
insert into price(amount, currency, deleted) values(1899.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Annibale Colombo Bed', 14, false);
insert into price(amount, currency, deleted) values(2499.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Annibale Colombo Sofa', 15, false);
insert into price(amount, currency, deleted) values(299.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Bedside Table African Cherry', 16, false);
insert into price(amount, currency, deleted) values(499.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Knoll Saarinen Executive Conference Chair', 17, false);
insert into price(amount, currency, deleted) values(799.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Wooden Bathroom Sink With Mirror', 18, false);
insert into price(amount, currency, deleted) values(1.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Apple', 19, false);
insert into price(amount, currency, deleted) values(12.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Beef Steak', 20, false);
insert into price(amount, currency, deleted) values(8.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Cat Food', 21, false);
insert into price(amount, currency, deleted) values(9.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Chicken Meat', 22, false);
insert into price(amount, currency, deleted) values(4.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Cooking Oil', 23, false);
insert into price(amount, currency, deleted) values(1.49, 'EUR', false);
insert into product(name, price_id, deleted) values('Engine Oil', 24, false);
insert into price(amount, currency, deleted) values(10.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Dog Food', 25, false);
insert into price(amount, currency, deleted) values(2.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Eggs', 26, false);
insert into price(amount, currency, deleted) values(14.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Fish Steak', 27, false);
insert into price(amount, currency, deleted) values(1.29, 'EUR', false);
insert into product(name, price_id, deleted) values('Green Bell Pepper', 28, false);
insert into price(amount, currency, deleted) values(0.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Green Chili Pepper', 29, false);
insert into price(amount, currency, deleted) values(6.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Honey Jar', 30, false);
insert into price(amount, currency, deleted) values(5.49, 'EUR', false);
insert into product(name, price_id, deleted) values('Ice Cream', 31, false);
insert into price(amount, currency, deleted) values(3.99, 'EUR', false);
insert into product(name, price_id, deleted) values('Juice', 32, false);
insert into price(amount, currency, deleted) values(2.49, 'EUR', false);
insert into product(name, price_id, deleted) values('Kiwi', 33, false);